### ISSUE TITLE
all.js hack job

### ISSUE THREAD

**Issue by OSPFNeighbour** [NSWSESMembers/Lighthouse#10]
Lighthouse/all/content/all.js

currently using a setInterval to wait for the var to exist before the code runs (var it needs is loaded from another script as the result of a ajax call)

also I do another ajax call to get the unit name. I couldn't find a var that stores it in the user session that is consistent across all beacon pages.

**Comment by lucanos** [comment]
I may be oversimplifying it, but wouldn't it be possible to store that in a cookie? Or at least cache the AJAX result in a cookie so you can reduce the number of API AJAX calls.

(As I said, I could be oversimplifying it, and be completely oblivious to the complexity of the problem...)

**Comment by sdunster** [comment]
Yeah, I haven't really looked much at this yet but I'd say using chrome storage/local storage is the way to go here. Feel free to hack at this if you like.

**Comment by OSPFNeighbour** [comment]
Yes you could store it, but you would need to hook the javascript call that fires when you change HQ so that you can update, which if you bind to the event the other binding is removed and things break.

As I said, i couldnt find the var where your HQ is stored, im sure its there somewhere. If we find that then I we dont need to make the call. I think it might be in the HQ manager function some where

**Comment by OSPFNeighbour** [comment]
Fixed with a global subscription on the user object. It's as good as it can get
