### ISSUE TITLE
NITC Register Export Error

### ISSUE THREAD

**Issue by outteridge** [NSWSESMembers/Lighthouse#162]
Lighthouse NITC Register Export fails with error:

Error loading page
Uncaught TypeError: x.nitc.get is not a function Line 2

**Comment by outteridge** [comment]
**Tech details**
Windows 11 Pro build 22621.1194
Microsoft Edge Version 109.0.1518.78 (Official build) (64-bit)

**Open NITC page**
{"notify":"init_tab"}
nitc:202
GET https://az416426.vo.msecnd.net/scripts/a/ai.0.js net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ nitc:202
setTimeout (async)
window.appInsights.instrumentationKey @ nitc:202
(anonymous) @ nitc:203
moment.min.js:23 
Deprecation warning: moment().subtract(period, number) is deprecated. Please use moment().subtract(number, period). See http://momentjs.com/guides/#/warnings/add-inverted-param/ for more info.
w @ moment.min.js:23
y @ moment.min.js:23
(anonymous) @ moment.min.js:270
StartDate @ base?v=4iLZ43iL6SJZmN_g0uFTfUA1y89Nn37oef2qOltC_cM1:1411
NonIncidentTimeCaptureFilterViewModel @ register?v=hl8hRvdQsCKf1koJYfCYXAagiCkfdkJV95XxJ2ZojTc1:391
(anonymous) @ register?v=hl8hRvdQsCKf1koJYfCYXAagiCkfdkJV95XxJ2ZojTc1:234
l @ jquery:1
c @ jquery:1
setTimeout (async)
(anonymous) @ jquery:1
c @ jquery:1
fireWith @ jquery:1
fire @ jquery:1
c @ jquery:1
fireWith @ jquery:1
ready @ jquery:1
bt @ jquery:1
all.js:2  Lighthouse extension v2023.01.06.01 Production version
Utils.ts:186 [2023-02-07T23:57:53.626Z] Information: WebSocket connected to wss://nswsesos-prod-signal.service.signalr.net/client/?hub=beacon&id=vEmb6SLdVfQfXDzfDd0q2g3653ac7e1&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhc3JzLnMuaWQiOiJsUUZHMERvT0FBQT0iLCJuYmYiOjE2NzU4MTQyNzEsImV4cCI6MTY3NTgxNzg3MSwiaWF0IjoxNjc1ODE0MjcxLCJhdWQiOiJodHRwczovL25zd3Nlc29zLXByb2Qtc2lnbmFsLnNlcnZpY2Uuc2lnbmFsci5uZXQvY2xpZW50Lz9odWI9YmVhY29uIn0.QHGtxh65xUUNGE9nYkGbvPu5XIv6XZZxcciKsBZSNsw.
all.js:1047 We are ready

**Open Lighthouse export**
Error loading page
Uncaught TypeError: x.nitc.get is not a function Line 2
_No console output_

**Comment by OSPFNeighbour** [comment]
Thanks,

I can see where the issue is and will get it sorted as soon as I can

**Comment by Rowantrek** [comment]
@OSPFNeighbour I have opened PR #164 to resolve this issue.

**Comment by Rowantrek** [comment]
> Collaborator

I assumed you would already have patched it locally; thought I'd open a PR incase that would help get a minor patch out quicker.

**Comment by Rowantrek** [comment]
@OSPFNeighbour Based on your previous release, I believe this can be closed now.
