### ISSUE TITLE
Team Team Leader

### ISSUE THREAD

**Issue by OSPFNeighbour** [NSWSESMembers/Lighthouse#26]
if theres one one person on a team the team leader is pretty fucking obvious..... we should auto tick the box if theres only one person.

**Comment by lucanos** [comment]
How about the first team member allocated to a team is made the Team Leader (which can be changed, obviously, as per standard beacon)?
This is typically how my Unit does it - they find out the TL first, and then they form the crew under them.

**Comment by OSPFNeighbour** [comment]
Yeah agreed.

Easy way to do this would be hook the submit button and then take the first
element in the team array and make it TL.

Easier than hooking every team member click.

**Comment by lucanos** [comment]
I'll play with a few solutions and put forward the most reliable/effective one (I can think of)

**Comment by OSPFNeighbour** [comment]
Any luck on this?

**Comment by lucanos** [comment]
Yeah, had it working a couple of days before. Have to look at my branches and try and merge it into commonjs.

**Comment by sdunster** [comment]
If you put a pull request up as it is currently (based on master) then I will rebase it onto commonjs for you.

**Comment by OSPFNeighbour** [comment]
Was added earlier in the year
