### ISSUE TITLE
Unable to add latest version to Chromium

### ISSUE THREAD

**Issue by sjcliffe** [NSWSESMembers/Lighthouse#40]
I noticed that the extension had not updated to the latest version on my home PC running Linux & Chromium so uninstalled it and tried to reinstall the latest version. It wouldn't install saying:

Package is invalid. Details: 'Could not load javascript 'Lighthouse/vendors/jquery/jquery-2.1.4.min.js' for content script'

**Comment by OSPFNeighbour** [comment]
Thanks mate. sounds like a case sensitive issue. will patch it asap.

**Comment by sdunster** [comment]
Closed by #41
