### ISSUE TITLE
Add NITC export/reports

### ISSUE THREAD

**Issue by sjcliffe** [NSWSESMembers/Lighthouse#42]
Currently beacon has none and Simon confirmed that none are planned in the near future so I'm going to look at adding some via Lighthouse.

**Comment by sjcliffe** [comment]
I have added NITC exporting to a cloned repo at https://github.com/sjcliffe/Lighthouse - let me know if you want a pull request.

I'll save the graphs for another day.

**Comment by OSPFNeighbour** [comment]
Sweet I'll have a play tomorrow.

I'm back at work tomorrow so will catch up on missed bugs and merge these
changes in

**Comment by sdunster** [comment]
Pull request for sure! Don't be afraid to contribute!

**Comment by sdunster** [comment]
Tracking in #45
