### ISSUE TITLE
checkAddressHistory() line 199

### ISSUE THREAD

**Issue by OSPFNeighbour** [NSWSESMembers/Lighthouse#46]
when loading job https://beacon.ses.nsw.gov.au/Jobs/69074

Uncaught TypeError: Cannot read property '3' of null
all.js:20 Focus

**Comment by sdunster** [comment]
Cannot repro building off of 59223f on Chrome for Mac Version 48.0.2564.97 (64-bit)

**Comment by sdunster** [comment]
Was caused by use of locale-based time APIs.
