### ISSUE TITLE
Make `gulp watch` work with `background.js`

### ISSUE THREAD

**Issue by sdunster** [NSWSESMembers/Lighthouse#62]

**Comment by OSPFNeighbour** [comment]
the structure of gulp is fucking weird. did my head in. my understanding was the you need getBundler to see the file for watch to work, but that didnt really work when i tried, gave up after about an hr

**Comment by OSPFNeighbour** [comment]
bump?

**Comment by OSPFNeighbour** [comment]
Fixed as we dropped gulp
