### ISSUE TITLE
add mouseover on ICEMS message words displays 'translation'

### ISSUE THREAD

**Issue by OSPFNeighbour** [NSWSESMembers/Lighthouse#63]
eg, inf = informant, aa = as above.
[icems.xlsx](https://github.com/NSWSESMembers/Lighthouse/files/142006/icems.xlsx)

**Comment by lucanos** [comment]
Do you have any example jobs to test against?

**Comment by sjcliffe** [comment]
https://beacon.ses.nsw.gov.au/Jobs/76541
https://beacon.ses.nsw.gov.au/Jobs/76543
https://beacon.ses.nsw.gov.au/Jobs/76554

**Comment by lucanos** [comment]
Example - https://beacon.ses.nsw.gov.au/Jobs/66843

**Inactive:**
![screen shot 2016-02-24 at 10 02 11 pm](https://cloud.githubusercontent.com/assets/126774/13283795/185bb016-db44-11e5-8032-fa6c4e104311.png)

**Active:**
![screen shot 2016-02-24 at 10 02 38 pm](https://cloud.githubusercontent.com/assets/126774/13283796/19788974-db44-11e5-8ccb-14d15d7341bd.png)
