### ISSUE TITLE
ICEMS_Dictionary selector is invalid in new beacon

### ISSUE THREAD

**Issue by OSPFNeighbour** [NSWSESMembers/Lighthouse#77]
The old selector of

  var $targetElements = $('.job-details-page div[data-bind="foreach: opsLogEntries"] div[data-bind="text: Text"]');

is invalid in the new beacon. it should be something like.

  var $targetElements = $('.job-details-page div[data-bind="foreach: opsLogEntries"] div[data-bind="text: $data"]');

**Comment by OSPFNeighbour** [comment]
@lucanos Do you want me to leave this with you or are you happy that I have correctly found the new selector as above?

**Comment by lucanos** [comment]
If you've identified the correct selector, and it tests OK, I'm happy for you to commit & land it. I'm on a "1st class" bus traveling back to BKK at the moment, so it would be a few hours until I could login and submit a PR myself.
